### ISSUE TITLE
关于自动下载配置文件

### ISSUE THREAD

**Issue by cjybyjk** [Sherlockwoo/DynamicWIPE#1]
platform的获取 **必须** 按照这个顺序: 
/proc/cpuinfo
ro.product.board
ro.board.platform
并且在获取到platform后应该停止
否则会出现获取到错误Soc型号的情况

**Comment by ghost** [comment]
感谢大佬指教。请教一下为什么要按照顺序获取？我看了一下你代码是按顺序的
我了解到的情况是有的机型比如某些三星机子
ro.product.board和
ro.board.platform
是不一样的。
所以目前的方案是检测三个数值都写入到一个变量，只要检测结果能匹配\*platform\*就算他的机型平台是此platform

**Comment by cjybyjk** [comment]
因为某些设备的ro.product.board和
ro.board.platform分别对应两个不同的，但是都在支持列表里的Soc(比如sdm636和sdm660)

之前有酷友反映过这个问题，我做了这个修改：[d5cc23a](https://github.com/cjybyjk/WIPE_flashable/commit/d5cc23a5772137fbd21fc70ba2708fb0edd10909) 

因为没怎么用过tasker，不知道你那样的判断方法是否会导致错误的匹配

**Comment by ghost** [comment]
目前这个判定方法即使不一样也是可以匹配成功的。但缺少特例的样本，就给标了个实验性功能

**Comment by cjybyjk** [comment]
ro.product.board对应的应该是device tree中的TARGET_BOOTLOADER_BOARD_NAME，而ro.board.platform对应的是TARGET_BOARD_PLATFORM

对于不同的Soc，它的BOARD_PLATFORM（主板型号）可能是相同的，因此我觉得不能简单的通配

**Comment by ghost** [comment]
举个例子，看能不能这把上面这段话理解成这样：
对于某版galaxy s8，有
"ro.product.board=universal8895"
"ro.board.platform=exynos5"
对于某版galaxy s9，有
"ro.product.board=universa19810"
"ro.board.platform=exynos5"
对于不同的Soc，它的ro.board.platform可能是相同的

**Comment by cjybyjk** [comment]
可以这么理解

**Comment by ghost** [comment]
Tasker里对上面的处理 
变量Platform(s8)=
universal8895
exynos5
Hardware:xxx
变量Platform(s9)=
universa19810
exynos5
Hardware:xxx
然后判断变量和已知的支持机型是否匹配（如\*universal8890\*）应该不会误判

**Comment by cjybyjk** [comment]
还有这种情况
Xiaomi whyred:
sdm636
sdm660
Hardware...

这样的话会取到哪个platform？

**Comment by ghost** [comment]
明白了！感谢回复（上面会取到判断语句中排在前位的platform 如果660在636之前就一直会取到660）

**Comment by cjybyjk** [comment]
实际上，从/proc/cpuinfo取到的值才是最准确的

**Comment by ghost** [comment]
遇到过3个变量都不一样的（没错又是三丧），这时候proc/cpuinfo匹配不到条件。
刚刚修改了下判断方法：构建SOC支持列表的数组，去掉proc/cpuinfo只依次取ro.product.board设为platformA和ro.board.platform设为platformB 
如果platformA在支持数组里platform就直接取其值，platformA不在platformB在则取platformB的值

**Comment by cjybyjk** [comment]
hhhhhhhhh这样也可以

话说三星的proc/cpuinfo是什么格式的? (因为build.prop是可以更改的，所以我认为还是不能保证准确性)

**Comment by ghost** [comment]
可以参考下[这个](https://github.com/pytorch/cpuinfo)

**Comment by BIGshaobing** [comment]
myURL  https://github.com/yc9559/cpufreq-interactive-opt/raw/master/vtools-powercfg/20180603/sd_835/powercfg.apk
ProfileStatus   0
WIPEStaus   /data/powercfg[200]: can't create /sys/devices/system/cpu/cpu4/online: Permission denied
Platform msm8996
大佬我想问一下我是努比亚z17，但是我的wipe自动一直失败是为什么，root权限已给，busybox也装了

**Comment by ghost** [comment]
@BIGshaobing 参考FAQ.8排除是否是自定义内核的原因

**Comment by BIGshaobing** [comment]
我看了一下是官方的内核，应该是满足要求的

**Comment by ghost** [comment]
@BIGshaobing 骁龙835的Platform应该是msm8998.方便把PlatformABC一起发上来吗

**Comment by BIGshaobing** [comment]
A：hardware : qualcomm technologies, inc msm8998
B:8998
C:8998

**Comment by BIGshaobing** [comment]
上面的8996是我输入错误了，抱歉

**Comment by ghost** [comment]
@BIGshaobing 看起来都正确 我也无能为力

**Comment by BIGshaobing** [comment]
我也不知道为什么文件下载不成功，那如果把文件直接写入进去可以吗
